### PR TITLE
Add a requirements file

### PR DESCRIPTION
**Pull request by Jc2k**
I'm using the latest libcloud release to do my testing which obviously isn't packaged. So here is the requirements file I used.

I can (but haven't) updated the documentation yet - I would like to change it to describe _only_ the virtualenv approach, thoughts?

### CODE REVIEW

**Comment by tobami** [comment]
Nice. setup.py is missing though, isn't it?

You could add it, and the updated doc as well, and then I can follow the exact steps you define so that they are "validated". That would be awesome.

**Comment by Jc2k** [comment]
Works without setup.py. Was reluctant to add one because I get quite strict with my packaging.

I would put all our dependencies in setup.py and have requirements.txt just reference the checked out code using -e.

**Comment by tobami** [comment]
Ok, go for it then!

**Comment by ericmachine88** [comment]
I tried the above and didn't work out :( any solutions?

**Pull request merged**
