### PR TITLE
InvalidCredsException is now in libcloud.common.types

### PR DESCRIPTION
**Pull request by cwarden**
Try to import InvalidCredsException from libcloud.common.types.  It was
moved in apache/libcloud@80ccbfe5a5fbc85062d96efacebcf8609f6fc9d7.

### CODE REVIEW

**Comment by tobami** [comment]
I think there is actually no reason for maintaining backwards compatibility. libcloud is a fairly new library, and versions from a year ago had not seen much widespread adoption. The changeset you reference is from before the 0.5 release, so I am voting for dropping compatibility for libcloud < 0.5

**Comment by cwarden** [comment]
Sounds good.

**Comment by tobami** [comment]
So are you going to remove the try: import and only use the newer import syntax?

**Comment by cwarden** [comment]
On Wed, Dec 14, 2011 at 02:30:21AM -0800, Miquel Torres wrote:

> So are you going to remove the try: import and only use the newer import syntax?

OK.  Just updated my branch.

Christian

**Pull request merged**
